version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto21
  build:
    commands:
      - echo "hi this is a test"
      - ./test.sh
      - ./infra/scripts/deploy-companion-chat-app.sh
cache:
  paths:
    - '/root/.gradle/caches/**/*'
    - '/root/.gradle/wrapper/**/*'