version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - echo "hi this is a test"
      - ./test.sh
      - ./infra/scripts/deploy-companion-api-lambda.sh
cache:
  paths:
    - '/root/.gradle/caches/**/*'
    - '/root/.gradle/wrapper/**/*'