AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Companion Chat App - Deployed using SAM

Globals:
  Function:
    Timeout: 30

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod

Resources:
  CompanionChatFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Join
        - '-'
        - - !Ref Environment
          - 'companion-chat-api-fn'
      MemorySize: 512
      Handler: com.companion.companionchat.LambdaHandler::handleRequest
      Runtime: java21
      CodeUri: "../build/distributions/companion-chat-0.0.1-SNAPSHOT.zip"
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            ApiId:
              Ref: CompanionChatApiGateway
            Path: /{proxy+}
            Method: ANY

  CompanionChatApiGateway:
    Type: AWS::Serverless::HttpApi
    Properties:
      Name: !Join
        - '-'
        - - !Ref Environment
          - 'companion-chat-api-gateway'

Outputs:
  CompanionChatEndpoint:
    Description: API Gateway endpoint URL for Companion Chat App
    Value: !Sub 'https://${CompanionChatApiGateway}.execute-api.${AWS::Region}.amazonaws.com/dev/'