AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: "companion-chat-cicd-sam-deploy"
      Description: "CI/CD Pipeline for companion-chat app"
      Source:
        Type: "NO_SOURCE"
        BuildSpec: "version: 0.2\n\nphases:\n  install:\n    runtime-versions:\n      java: corretto21\n  build:\n    commands:\n      - echo \"hi this is a test\"\n      - ./test.sh\n      - ./infra/scripts/deploy-companion-api-lambda.sh\ncache:\n  paths:\n    - '/root/.gradle/caches/**/*'\n    - '/root/.gradle/wrapper/**/*'"
        InsecureSsl: false
      ServiceRole: "arn:aws:iam::484907525991:role/service-role/codebuild-companion-chat-sam-deploy-service-role"
      Artifacts:
        Type: "NO_ARTIFACTS"
      TimeoutInMinutes: 15
      EncryptionKey: "arn:aws:kms:eu-west-2:484907525991:alias/aws/s3"
      Environment:
        ComputeType: "BUILD_GENERAL1_SMALL"
        Image: "aws/codebuild/amazonlinux2-x86_64-standard:5.0"
        Type: "LINUX_CONTAINER"
        ImagePullCredentialsType: "CODEBUILD"
      LogsConfig:
        CloudWatchLogs:
          Status: ENABLED
          GroupName: "/aws/codebuild/companion-chat-cicd-sam-deploy"
        S3Logs:
          Status: DISABLED
          EncryptionDisabled: false

  CodeBuildLogGroup:
    Type: "AWS::Logs::LogGroup"
    Properties:
      LogGroupName: !Sub '/aws/codebuild/companion-chat-cicd-sam-deploy'
      RetentionInDays: 5